import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  console.log(props.Refuse_collection_dates);

  return (
    <div className={styles.container}>
      <Head>
        <title>Bin Days!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bin collection days</h1>
        <h2>For 36 Muswell Avenue</h2>

        <section>Today is {new Date().toDateString()}</section>

        <ul>
          {props.Refuse_collection_dates.map((item) => {
            const topic = item._.replace(/<[^>]*>?/gm, "");
            return (
              <li key={topic}>
                <section>
                  <h3>{topic}</h3>
                  <div>Last Collection: {item.Last_Collection}</div>
                  <div>Next Collection: {item.Next_Collection}</div>
                </section>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://erkinunlu.net"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by your friendly neighbour Erkin ❤️
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch(
    "https://my.haringey.gov.uk/getdata.aspx?RequestType=LocalInfo&ms=mapsources/MyHouse&format=JSON&group=Property%20details|Refuse%20collection%20dates&uid=100021204359"
  );

  const data = await res.json();
  return {
    props: data.Results ?? {},
  };
}
